#+OPTIONS: toc:nil H:10 tex:t num:1
#+STARTUP: hidestars indent
#+INCLUDE: personal-info.org
#+LaTeX_HEADER: \usepackage{mycv}
#+LaTeX_HEADER: \hypersetup{colorlinks=true, urlcolor={url-gray}}
#+LaTeX_CLASS_OPTIONS: [letterpaper]
#+LaTeX_HEADER: \usepackage{enumitem}
#+LaTeX_HEADER: \setlist{leftmargin=0.25in,nosep}

{{{HEADER}}}

@@latex:\begin{center} {\Large Technology Advisor --- Database Administrator --- Systems Specialist} \end{center} @@
* Skills
+ CRM upkeep :: Most familiar with *Raiser's Edge*.
+ Sensitivity awareness :: Track record of properly handling sensitive constituent info.
+ *Understanding nonprofits* :: Providing value-adds through active listening and systems thinking.
* Project IMPRESS- IMPact Realized by Enabling Self-Service
I'm most proud of enabling self-service for...

** Data Administrators
*** Evergreen Student Elections
+ /Old process/ :: Elections comissioners had to rely on IT for
  reports. No ability to conduct polls despite need.
+ /Improvement/ :: Rebuilt app for comissioners, allowing
  self-serve reports on in-progress and completed elections.
+ /Bonus/ :: New features included being able to conduct polls and
  categorize elections.
** Frontline Fundraisers
*** Advancement
+ /Old process/ :: Frontline staff used to wait weeks for reports.
+ /Improvement/ :: Served as a *subject matter expert for
  Raiser's Edge* when staff had trouble.
+ /Bonus/ :: Managed dynamic queries in anticipation of campaign events,
  created new queries when needed.
** Board Members
*** The S&A Board- Student Leadership Activity Reporting
+ /Old process/ :: The Board's old process relied solely on Student
  Activities leadership to catch mistakes before Board meetings, else
  groups would have to appear before the Board more than once with
  corrected budgets.
+ /Improvement/ :: Sped up our review process by introducing self-service
  budget packets for Board members.
+ /Bonus/ :: I *reduced our group defect rate by a factor of 10*
  through streamlining budget request process.
** REEF Kitchens
*** REEF Fulfillment Improvement Initiatives
+ /Old process/ :: Inefficiencies in fulfillment led to unnecessary busywork.
+ /Improvement/ :: Implemented system which brought 3 hour long
  fulfillment process step to <1 hour for field ops.
+ /Bonus/ :: Made this system easy to deploy for other West US MSA
  managers without them needing my involvement.
* Experience
** Executive Assistant
*** REEF (Mar 2021 - Present)
Built workflows for teams of ~2 dozen atop the Microsoft Power Suite
on behalf of the Executive Production Chef.
** Sharepoint Developer, Tacoma Power
*** Tacoma Public Utilities (May 2021 - May 2022)
Subject matter expert for ~100 people on SharePoint Online during
citywide transition from SharePoint on-prem.
** Lynda.com CRM Database Fellow
*** The Evergreen Foundation (Sep 2017 - Jun 2019)
Shadowed Assoc. Director of Adv. Services, who led the
implementation of Raiser's Edge for team of 1 dozen.
** Office Manager
*** Evergreen Services and Activities Fee Allocation Board (Apr 2017 - Jun 2018)
Supported ten Board members stewarding a 7-figure budget with ~50
funded Registered Student Organizations.
* Education
** BS, Networked and Social Systems Engineering
*** The Evergreen State College
** BA, Liberal Arts and Sciences/Liberal Studies
*** Olympia, WA
** Associate in Arts
*** Green River College, Auburn, WA
** Certified Continuous Improvement Manager (CCIM)
*** Management & Strategy Institute
* Passion
 I care a lot about manageable sustainability! Inspired by nature's
 "closing the loop" and minimization of waste.
