#+TITLE: Networked + Social Systems Engineer
#+AUTHOR: Brandon Ellington
#+email: branjam4@gmail.com

# CV theme - options include: 'casual' (default), 'classic', 'oldstyle' and 'banking'
#+CVSTYLE: casual
# CV color - options include: 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'
#+CVCOLOR: orange

#+ADDRESS: Seattle, Washington
#+MOBILE: (206) 450-1343
#+HOMEPAGE: branjam.dev
#+GITHUB: branjam4
#+LINKEDIN: brandon-ellington
#+PHOTO: profile-small.jpg

* Education
** Bachelor's of Science
:PROPERTIES:
:FROM: <2016-04-01>
:TO: <2020-12-01>
:LOCATION: Olympia, WA
:EMPLOYER: The Evergreen State College
:CV_ENV:   cventry
:END:   
Networked + Social Systems Engineering
** Bachelor's of Arts
:PROPERTIES:
:FROM: <2016-04-01>
:TO: <2020-12-01>
:LOCATION: 
:EMPLOYER: The Evergreen State College
:CV_ENV:   cventry
:END:
Philosophy
* Experience
** Software Internship- Web Development
:PROPERTIES:
:FROM: <2017-06-01>
:TO: <2017-09-01>
:CV_ENV:   cventry
:LOCATION: Enterprise Development Team
:EMPLOYER: The Evergreen State College
:END:
+ Enterprise web application rewrite with PHP and Drupal.
+ Increased code maintainability through improving documentation, test-driven
  development, and object-relational mapping.
+ Learned how to speed up the development cycle through sprint planning sessions
  and other Agile methodologies.
+ Learned how user stories reduce the feedback loop between ideation and
  execution through requirements gathering and test-driven development.
* Projects
** VIP-Dev Environment Project
:PROPERTIES:
:FROM: <2018-05-01>
:TO: <2020-12-01>
:LOCATION: Personal
:END:
/Virtualized Integrated "Personal Development" Environment/

1. Created an extended cognitive system for development and personal information
   management utilizing Org-mode within Emacs.
2. Containerized system within Docker; alternate version of the system
   virtualized within a qemu image.
3. Decreased cognitive switching by 50-100% for tasks such as locating
   documentation, test-driven development, and keeping code notebooks.
4. Increased knowledge capture from dozens of ideas per year to hundreds through
   interactive journals and literate programming.


Repo: https://github.com/branjam4/branos-provisioning.git
** Communication Optimization
:PROPERTIES:
:FROM: <2017-04-01>
:TO: <2018-09-01>
:LOCATION: With public organizations
:EMPLOYER: Campus Leadership
:END:
1. Advocated for technology upgrades and visioning based on systems thinking and
   led execution of the project within two related organizations.
2. Implementation increased weekly communications among colleagues to almost
   daily, improving project coordination and group resiliency.
3. Technology upgrades improved user experience and reduced repetitive tasks for
   office staff from five hours to less than one hour.
** Financial Insecurity Perceptual Improvement
:PROPERTIES:
:FROM: <2017-04-01>
:TO: <2017-06-01>
:LOCATION: Public nonprofit client
:END:
1. Led a team collecting social data, building a semi-automated sentiment
   analysis algorithm within Python and R in collaboration with a nonprofit.
2. Used insights to help our client improve community outreach efforts and
   enhance collaborations with other organizations.
3. Initiative and detailed requirements gathering led to increased understanding
   of the technical goals of the project.

* Coursework
*Computer Science Courses*

Digital Logic, Computer Architecture, Discrete Math, Python, Java, Clojure.
Basic data structures and algorithms. Intermediate computer networking.

*Modelling Change*

Self-study which applied network theory, systems theory, and complexity analysis
to improving organizational agility. Learned how engagement and inclusivity
increase team productivity. Came to appreciate the value of "computational
kindness-" making decisions as simple to mentally and emotionally process as
possible.

* Awards, Activities, and Achievements
+ Jun. 2019 :: Innovation Across the Americas Award Recipient           
+ Oct. 2018 :: Equity Honors Nominee                                    
+ 2017-2019 :: Lynda.com CRM Advancement Fellow                         
+ 2017-2018 :: Student Representative to the Evergreen Board of Trustees
+ Jun. 2017 :: Computer Engineering Scholarship Recipient                         
+ 2017-2018 :: Presidential Equity Advisor                              
* Local Variables :noexport:
:PROPERTIES:
:VISIBILITY: folded
:END:
#+begin_src elisp
(defun bran/org-export-to-moderncv ()
  (let ((filename (concat (file-name-sans-extension buffer-file-name) ".tex")))
    (org-export-to-file 'moderncv filename)
    (org-latex-compile filename)))
#+end_src

#+BEGIN_EXAMPLE org
,# Local Variables:
,# after-save-hook: bran/org-export-to-moderncv
,# End:
#+END_EXAMPLE
